name: Bug Report
description: 报告一个 Bug 或问题
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您报告 Bug！请填写以下信息帮助我们更好地定位和修复问题。

  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: 详细描述您遇到的问题
      placeholder: 告诉我们发生了什么！
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 重现步骤
      description: 详细的重现步骤
      placeholder: |
        1. 打开扩展
        2. 点击 '...'
        3. 滚动到 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 描述您期望发生的行为
      placeholder: 应该发生什么？
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 描述实际发生的行为
      placeholder: 实际发生了什么？
    validations:
      required: true

  - type: dropdown
    id: chrome-version
    attributes:
      label: Chrome 版本
      description: 您使用的 Chrome 浏览器版本？
      options:
        - Chrome 120+
        - Chrome 110-119
        - Chrome 100-109
        - Chrome 90-99
        - 其他 (请在下方说明)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 您使用的操作系统？
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Linux
        - 其他 (请在下方说明)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 任何其他有助于解决问题的信息
      placeholder: |
        - 扩展版本
        - 错误截图
        - 控制台错误信息
        - 其他相关信息

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 提交前请确认以下内容
      options:
        - label: 我已经搜索了现有的 Issues，没有找到相同的问题
          required: true
        - label: 我已经阅读了贡献指南
          required: true
